### PR TITLE
Fix compatibility with pygccxml-1.8

### PR DESCRIPTION
**Pull request by cls**
It seems that some submodules of `pygccxml.declaration` are meant to be internal, but they are being used in pybindgen, and some refactoring in pygccxml-1.8 has broken compatibility. This patch should fix it by avoiding these internal modules.

### CODE REVIEW

**Comment by gjcarneiro** [comment]
To be honest, I am unable to properly test this since on my system CastXML doesn't work, I am affected by [this issue](https://github.com/gimli-org/gimli/issues/40).  Which makes me think perhaps CastXML is not ready for prime time.

Let me keep this PR on hold until Ubuntu fix their CastXML package...

**Comment by cls** [comment]
I'm not using CastXML either, as it's not packaged for Debian Jessie, but this seems to work for GCC-XML:

```py
gccxml_options = {
    'xml_generator': 'gccxml',
    'xml_generator_path': '/usr/bin/gccxml',
}
module_parser = pybindgen.gccxmlparser.ModuleParser(module_name)
module = module_parser.parse(header_files, gccxml_options=gccxml_options)

**Comment by gjcarneiro** [comment]
Unfortunately gccxml is not available for Ubuntu anymore.

**Comment by gjcarneiro** [comment]
I tried this in docker `debian:jessie`, but no much luck getting this branch to work:
```
[ 5/24] command (${PYTHON}): tests/foomodulegen-auto.py tests/foo.h -> build/tests/foomodule2.cc build/tests/foomodulegen_generated.py
PYTHON_INCLUDES: "['/usr/include/python2.7', '/usr/include/x86_64-linux-gnu/python2.7']"
/usr/local/lib/python2.7/dist-packages/pygccxml/utils/utils.py:491: DeprecationWarning: gccxml_configuration_t is deprecated. Please use xml_generator_configuration_t instead. This will be removed in version 1.9.0
  DeprecationWarning)
INFO Parsing source file "tests/foo.h" ... 
/usr/local/lib/python2.7/dist-packages/pygccxml/declarations/typedef.py:58: DeprecationWarning: typedef_t.type is deprecated.
Please use typedef_t.decl_type instead.
  "Please use typedef_t.decl_type instead.", DeprecationWarning)
/usr/local/lib/python2.7/dist-packages/pygccxml/declarations/typedef.py:58: DeprecationWarning: typedef_t.type is deprecated.
Please use typedef_t.decl_type instead.
  "Please use typedef_t.decl_type instead.", DeprecationWarning)
/usr/local/lib/python2.7/dist-packages/pygccxml/declarations/typedef.py:58: DeprecationWarning: typedef_t.type is deprecated.
Please use typedef_t.decl_type instead.
  "Please use typedef_t.decl_type instead.", DeprecationWarning)
/usr/local/lib/python2.7/dist-packages/pygccxml/declarations/typedef.py:58: DeprecationWarning: typedef_t.type is deprecated.
Please use typedef_t.decl_type instead.
  "Please use typedef_t.decl_type instead.", DeprecationWarning)
Traceback (most recent call last):
  File "tests/foomodulegen-auto.py", line 68, in <module>
    main()
  File "tests/foomodulegen-auto.py", line 65, in main
    my_module_gen()
  File "tests/foomodulegen-auto.py", line 36, in my_module_gen
    module_parser.scan_types()
  File "/code/pybindgen/gccxmlparser.py", line 790, in scan_types
    self._scan_namespace_types(self.module, self.module_namespace, pygen_register_function_name="register_types")
  File "/code/pybindgen/gccxmlparser.py", line 1189, in _scan_namespace_types
    for templ_param in template_parameters]
  File "/code/pybindgen/gccxmlparser.py", line 108, in find_declaration_from_name
    decl = pygccxml.declarations.declarations.impl_details.find_value_type(global_ns, declaration_name)
AttributeError: 'module' object has no attribute 'declarations'
```

**Comment by anthrotype** [comment]
bump @gjcarneiro 🙏

**Comment by cls** [comment]
I'm no longer using pybindgen, but the error @gjcarneiro posted should be fixed by replacing `pygccxml.declarations.declarations` with `declarations` — an editing mistake on my part.

**Comment by anthrotype** [comment]
@cls ok, thanks

> I'm no longer using pybindgen

Did you maybe find an alternative?

**Comment by gjcarneiro** [comment]
I think that the module `pybindgen.castxmlparser` fixed compatibility with latest pygccxml. Closing this.

**Pull request closed without merging**
