### PR TITLE
Fixing 2 memory leaks. Comments in the code give more details

### PR DESCRIPTION
**Pull request by lowaa**
Not sure if this is the right way to fix these issues but they have solved the problem for my use case.

### CODE REVIEW

**Comment by gjcarneiro** [comment]
Almost certainly not the right approach to fix.  And I don't quite understand the problem.  A unit test would go a long way to describing the problem, so that even if the patch is not correct I may be able to come up with a better solution.

**Comment by lowaa** [comment]
Thanks for the feedback. I'll make a unit test when I have some free time

**Comment by cosnicolaou** [comment]
I fixed this same issue in a different way in #27, I added a keyword to allow the user to control this behaviour. The current waf tests seem very out of date and won't compile/run for me on a mac with catalina - is that expected?

**Comment by gjcarneiro** [comment]
Indeed I prefer #27 better, seems safer to only do this when explicitly requested.  So I'm going to close it in favour of #27.

**Pull request closed without merging**
